development:
  cloud_name: fypeventapp
  api_key: '942528919821819'
  api_secret: xYZNKn9PgSlDBW9cPPbgSw-WJ6M
  enhance_image_tag: true
  static_image_support: false
  
production:
  cloud_name: fypeventapp
  api_key: '942528919821819'
  api_secret: xYZNKn9PgSlDBW9cPPbgSw-WJ6M
  enhance_image_tag: true
  static_image_support: true
